# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'windows-2019'

container: mcr.microsoft.com/windows/servercore:ltsc2019

steps:
- script: set


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $connectTestResult = Test-NetConnection -ComputerName azcicdstorage2021.file.core.windows.net -Port 445
      if ($connectTestResult.TcpTestSucceeded) {
      
        cmd.exe /C "cmdkey /add:`"azcicdstorage2021.file.core.windows.net`" /user:`"Azure\azcicdstorage2021`" /pass:`"4IdW9qnYe5amzFCLZfOf5P0olXfJC6hAiM3p4TqkAjaL9DwsWYzaE7VeG1VXaBfOzb2P0Zxe5fXGCmnauxWt5g==`""
        New-PSDrive -Name Z -PSProvider FileSystem -Root "\\azcicdstorage2021.file.core.windows.net\workingfolder" -Persist
        } 
        else {
        Write-Error -Message "Unable to reach the Azure storage account via port 445. Check to make sure your organization or ISP is not blocking port 445, or use Azure P2S VPN, Azure S2S VPN, or Express Route to tunnel SMB traffic over a different port."
        } 
      get-content Z:\1.txt
      copy-item Z:\BuildTools\InstallShield2020R3StandaloneBuild.exe -Destination .
      .\InstallShield2020R3StandaloneBuild.exe /s /v"INSTALLLEVEL=101 SABCONTAINER=1 /qn"
      
      #copy IDK
      New-Item -ItemType directory -Path C:\Tools
      
      copy-item "Z:\BuildTools\IDK\AspenTech IDK.msi" -Destination C:\Tools
      copy-item "Z:\BuildTools\IDK\new UI fix\ATMaster.msi" -Destination C:\Tools
      dir C:\Tools
      #start-process msiexec.exe -Wait -ArgumentList '/I "C:\Tools\AspenTech IDK.msi" /qn'   
      msiexec.exe /I "C:\Tools\AspenTech IDK.msi" /qn
      start-sleep -s 40
    
      cd "C:\Program Files (x86)\AspenTech\IDK"
      dir
      copy-item C:\Tools\ATMaster.msi -Destination "C:\Program Files (x86)\AspenTech\IDK\Templates"
      start-sleep -s 40
      #ipconfig /all
      #Build Suite
      cd C:\Tools
      copy-item "Z:\P4\idk_installation\V12.1\Int\AES\SetupFiles\aspenONEEngineeringV12.1_x64.mic" -Destination "C:\Tools" 
      copy-item -path "Z:\Release\msi\Aspen Operator Training V12.1 (64bit)\*" -Destination "C:\Tools\Aspen Operator Training V12.1 (64bit)"
      Get-ChildItem "Z:\Release\msi\Aspen Operator Training V12.1 (64bit)"
      dir
      cd "C:\Tools\Aspen Operator Training V12.1 (64bit)"
      dir
      start-process -FilePath "C:\Program Files (x86)\AspenTech\IDK\Bin\BuildSuite.exe" -Wait -ArgumentList C:\Tools\aspenONEEngineeringV12.1_x64.mic
      
     
      #copy-item -path aspenONEEngineeringV12.1_x64 -Destination "Z:\Release\Suite\Current" -Recurse

- task: CmdLine@2
  inputs:
    script: |
      cd C:\Tools
      dir
      echo Hello world



